In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('heart.csv')
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trtbps    303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalachh  303 non-null    int64  
 8   exng      303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64  
 11  caa       303 non-null    int64  
 12  thall     303 non-null    int64  
 13  output    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [4]:
df.shape

(303, 14)

In [5]:
df.isna().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [6]:
df['output'].value_counts()

output
1    165
0    138
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
Y=df["output"]
X=df.drop(["output"],axis=1)


In [8]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=10)

In [9]:
LinearReg = LinearRegression()
LinearReg

LinearRegression()

In [10]:
LinearReg.fit(x_train, y_train)

LinearRegression()

In [11]:
predictions = LinearReg.predict(x_test)

In [12]:
predictions

array([ 0.10690199,  0.55505336,  0.40294865,  0.68204686,  0.23538997,
        0.66055725,  0.71417326,  0.65926787,  0.78863888,  0.2172552 ,
        0.93929752,  0.10107095,  0.62693672,  0.46370275,  0.17305659,
        0.41956346, -0.08202548, -0.142378  ,  0.81831998,  0.17786907,
        0.05046057,  0.81169748,  0.60541793,  0.90408335,  0.19293013,
        0.11192105, -0.14215794,  0.23223908,  0.96051394, -0.18474803,
        0.83879182,  0.24487762,  0.06817232,  0.41506667, -0.12435942,
        0.29024589,  0.63982586,  0.52170843,  0.8320797 ,  0.19373921,
        0.34085441,  0.13773381,  0.69449696,  0.57873846,  1.00283452,
        0.53872082,  0.66943469,  0.77576822,  0.6637762 ,  0.61361022,
        0.48122393,  0.81452513,  0.13270421,  0.41617882,  1.11776317,
        0.6095759 ,  0.64580551,  0.69442012, -0.0272208 ,  0.12059588,
        0.64180426])

In [13]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [14]:
LinearRegression_MAE = mean_absolute_error(y_test, predictions)
LinearRegression_MSE = mean_squared_error(y_test, predictions)
LinearRegression_R2 = r2_score(y_test, predictions)

In [15]:
print("MAE=",LinearRegression_MAE )
print("MSE=",LinearRegression_MSE )
print("R2=",LinearRegression_R2 )


MAE= 0.31064814500994936
MSE= 0.142176342178596
R2= 0.4186393744543343


In [16]:
Report = pd.DataFrame({
    'Metric': ['MAE', 'MSE', 'R2'],
    'Linear Regression': [LinearRegression_MAE, LinearRegression_MSE, LinearRegression_R2]
})
Report

Metric  Linear Regression
0    MAE           0.310648
1    MSE           0.142176
2     R2           0.418639

In [17]:
from sklearn.neighbors import KNeighborsRegressor

In [18]:
KNN = KNeighborsRegressor(n_neighbors=4)
KNN.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=4)

In [19]:
predictions = KNN.predict(x_test)

In [20]:
predictions

array([0.75, 0.25, 0.5 , 0.5 , 0.25, 1.  , 0.75, 0.5 , 0.5 , 0.5 , 0.75,
       0.5 , 0.5 , 1.  , 0.5 , 1.  , 0.75, 0.  , 1.  , 0.25, 0.25, 0.5 ,
       0.75, 0.5 , 0.  , 0.  , 0.5 , 0.  , 0.5 , 0.5 , 0.75, 0.5 , 0.25,
       0.5 , 0.75, 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.75, 0.5 , 0.5 , 1.  ,
       1.  , 0.75, 1.  , 1.  , 0.75, 0.75, 0.5 , 1.  , 0.5 , 0.75, 0.25,
       1.  , 0.25, 0.75, 0.  , 0.5 , 1.  ])

In [21]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score
binary_predictions = [round(pred) for pred in predictions]
KNN_Accuracy_Score = accuracy_score(y_test, binary_predictions)
KNN_JaccardIndex = jaccard_score(y_test, binary_predictions)
KNN_F1_Score = f1_score(y_test, binary_predictions)
Report = pd.DataFrame({
    'Metric': ['Accuracy', 'Jaccard', 'F1'],
    'KNN Regression': [KNN_Accuracy_Score, KNN_JaccardIndex, KNN_F1_Score]
})
Report 

Metric  KNN Regression
0  Accuracy        0.639344
1   Jaccard        0.388889
2        F1        0.560000

In [22]:
from sklearn.tree import DecisionTreeRegressor

In [23]:
Tree = DecisionTreeRegressor()
Tree.fit(x_train, y_train)

DecisionTreeRegressor()

In [24]:
predictions = Tree.predict(x_test) 
predictions

array([1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 0.])

In [25]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score
# Convert regression predictions to binary (if needed)
binary_predictions_tree = [round(pred) for pred in predictions]

Tree_Accuracy_Score = accuracy_score(y_test, binary_predictions_tree)
Tree_JaccardIndex = jaccard_score(y_test, binary_predictions_tree)
Tree_F1_Score = f1_score(y_test, binary_predictions_tree)

Report = pd.DataFrame({
    'Metric': ['Accuracy', 'Jaccard', 'F1'],
    'Decision Tree': [Tree_Accuracy_Score, Tree_JaccardIndex, Tree_F1_Score]
})
Report

Metric  Decision Tree
0  Accuracy       0.754098
1   Jaccard       0.594595
2        F1       0.745763

In [26]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [27]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(solver='liblinear')
LR.fit(x_train, y_train)

LogisticRegression(solver='liblinear')

In [28]:
predictions = LR.predict(x_test)

In [29]:
predict_proba = LR.predict_proba(x_test)
predict_proba

array([[0.99589666, 0.00410334],
       [0.24226574, 0.75773426],
       [0.92266945, 0.07733055],
       [0.99263766, 0.00736234],
       [0.97186104, 0.02813896],
       [0.99560141, 0.00439859],
       [0.98918495, 0.01081505],
       [0.35595881, 0.64404119],
       [0.99534889, 0.00465111],
       [0.01383027, 0.98616973],
       [0.62643241, 0.37356759],
       [0.90326676, 0.09673324],
       [0.20434259, 0.79565741],
       [0.69736854, 0.30263146],
       [0.75839431, 0.24160569],
       [0.0550399 , 0.9449601 ],
       [0.01225996, 0.98774004],
       [0.98385711, 0.01614289],
       [0.50540452, 0.49459548],
       [0.16942679, 0.83057321],
       [0.02065297, 0.97934703],
       [0.97851632, 0.02148368],
       [0.23297291, 0.76702709],
       [0.02470081, 0.97529919],
       [0.01651661, 0.98348339],
       [0.26585962, 0.73414038],
       [0.99565039, 0.00434961],
       [0.01649015, 0.98350985],
       [0.1284249 , 0.8715751 ],
       [0.00775658, 0.99224342],
       [0.

In [30]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score, log_loss
LR_Accuracy_Score = accuracy_score(y_test, predictions)
LR_JaccardIndex = jaccard_score(y_test, predictions)
LR_F1_Score = f1_score(y_test, predictions)
LR_Log_Loss = log_loss(y_test, predict_proba)

In [31]:
from sklearn.svm import SVC
SVM = SVC()
SVM.fit(x_train, y_train)

SVC()

In [32]:
predictions4 = SVM.predict(x_test)
predictions4

array([1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score

SVM_Accuracy_Score = accuracy_score(y_test, predictions)
SVM_JaccardIndex = jaccard_score(y_test, predictions)
SVM_F1_Score = f1_score(y_test, predictions)

In [34]:
Report = pd.DataFrame({
    'Model': ['K-Nearest Neighbors', 'Decision Tree', 'Logistic Regression', 'Support Vector Machine'],
    'Accuracy': [ KNN_Accuracy_Score, Tree_Accuracy_Score, LR_Accuracy_Score, SVM_Accuracy_Score],
    'Jaccard Index': [ KNN_JaccardIndex, Tree_JaccardIndex, LR_JaccardIndex, SVM_JaccardIndex],
    'F1 Score': [ KNN_F1_Score, Tree_F1_Score, LR_F1_Score, SVM_F1_Score],
    'Log Loss': [ None, None, LR_Log_Loss, None]
})
Report

Model  Accuracy  Jaccard Index  F1 Score  Log Loss
0     K-Nearest Neighbors  0.639344       0.388889  0.560000       NaN
1           Decision Tree  0.754098       0.594595  0.745763       NaN
2     Logistic Regression  0.754098       0.634146  0.776119  0.531239
3  Support Vector Machine  0.754098       0.634146  0.776119       NaN